name: Cron Test

on:
  schedule:
    - cron: "21,26,31,36 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print time
        run: |
          date -u
          echo "Cron works"